name: pelican
channels:
  - defaults
  - conda-forge
dependencies:
  - colorama
  - paramiko
  - matplotlib
  - numpy
  - scipy
  - pelican
  - pip
  - pip:
    - google-api-python-client
    - google-auth-httplib2
    - google-auth-oauthlib
    - pelican-youtube

